### PR TITLE
Fixes Uncaught TypeError on getDevice due to default being empty

### LINKED ISSUE #21572: [Bug] PHP Fatal error: Uncaught TypeError: DeviceDetector\DeviceDetector::getDevice(): Return value must be of type ?int, string returned
### What happened?

In /var/www/html/vendor/matomo/device-detector/DeviceDetector.php:492

I don't have more information. I assume this causes some tracking requests to not be tracked.

### What should happen?

No fatal error

### How can this be reproduced?

Unclear.

Wonder if it only happens when Device information is cached using https://github.com/matomo-org/plugin-DeviceDetectorCache/

### Matomo major version

Matomo 5

### Matomo minor or patch Version

0

### PHP version

.

### Server operating system

.

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

.

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Fixes Uncaught TypeError on getDevice due to default being empty
Fixes: https://github.com/matomo-org/matomo/issues/21572

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by snake14** [comment]
@AltamashShaikh It looks like the test case that I added needs to be updated corresponding to your change.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh It looks like the test case that I added needs to be updated corresponding to your change.

@snake14 Yes, updated and added 1 more new case

**Review by snake14 — APPROVED** [review]
Looks alright to me. I don't see any errors when I view Device Detection in my local instance.

File: CachedEntry.php [hunk 1]
```diff
@@ -28,10 +28,10 @@ public function __construct(string $userAgent, $clientHints, array $values)
...
 
-        $this->bot = $values['bot'] ?? '';
+        $this->bot = $values['bot'] ?? null;
         $this->brand = $values['brand'] ?? '';
-        $this->client = $values['client'] ?? '';
-        $this->device = $values['device'] ?? '';
+        $this->client = $values['client'] ?? null;
+        $this->device = $values['device'] ?? null;
         $this->model = $values['model'] ?? '';
         $this->os = $values['os'] ?? '';
```
Comment (sgiehl) [inline CachedEntry.php]: That one better should be null as well. 
```suggestion
        $this->os = $values['os'] ?? null;
```

Comment (AltamashShaikh) [reply CachedEntry.php]: done :+1:

**Review by tsteur — APPROVED** [review]
Nice, and thanks for adding the test 👍 💯

**Review by sgiehl — APPROVED** [review]
